# Generated by Django 5.1.7 on 2025-04-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_wish_cost_estimate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wish",
            name="value",
            field=models.CharField(
                blank=True,
                choices=[
                    ("⭐️", "⭐️"),
                    ("⭐️⭐️", "⭐️⭐️"),
                    ("⭐️⭐️⭐️", "⭐️⭐️⭐️"),
                    ("⭐️⭐️⭐️⭐️", "⭐️⭐️⭐️⭐️"),
                    ("⭐️⭐️⭐️⭐️⭐️", "⭐️⭐️⭐️⭐️⭐️"),
                ],
                default="⭐️⭐️⭐️",
                max_length=10,
                null=True,
            ),
        ),
    ]
