version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env.local
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A settings worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env.local

  celery-beat:
    build: .
    command: celery -A settings beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env.local

volumes:
  postgres_data:
