from setuptools import setup, find_packages

setup(
    name="django-project-template",
    version="0.1.0",
    description="A modern Django project template",
    author="Valor Engels",
    author_email="your_email@example.com",
    url="https://github.com/yourusername/django-project-template",
    packages=find_packages(),
    include_package_data=True,
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Web Environment",
        "Framework :: Django",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    ],
    python_requires=">=3.8",
    install_requires=[
        "Django>=4.0",
        "djangorestframework",
        "psycopg2",
        "django-htmx",
        "celery",
        "django-storages",
        "boto3",
    ],
    scripts=["build.sh"],
)