from django.db import models
from common.behaviors.timestampable import (
    Timestampable,
)  # Adds created_at and updated_at fields
from common.behaviors.uuidable import UUIDable  # Adds a UUID primary key field
from common.behaviors.annotatable import Annotatable  # Adds annotation capabilities
from .data_summary import DataSummary  # Import DataSummary model


# Model representing a comparison between two DataSummary records.
class SummaryComparison(UUIDable, Timestampable, Annotatable):

    # First DataSummary to compare
    summary_1 = models.ForeignKey(
        DataSummary,
        on_delete=models.CASCADE,
        related_name="comparisons_as_first",
        help_text="The first summary to be compared.",
    )

    # Second DataSummary to compare
    summary_2 = models.ForeignKey(
        DataSummary,
        on_delete=models.CASCADE,
        related_name="comparisons_as_second",
        help_text="The second summary to be compared.",
    )

    # Comparison result as text
    comparison_result = models.TextField(
        help_text="The text of the comparison generated by ChatGPT."
    )

    # Type of comparison
    comparison_type = models.CharField(
        max_length=50,
        default="week-over-week",
        help_text="The type of comparison (e.g., 'week-over-week').",
    )

    def __str__(self):
        return f"Comparison: {self.summary_1.label} vs {self.summary_2.label}"

    class Meta:
        ordering = ["-created_at"]  # Order by most recently created
        constraints = [
            models.CheckConstraint(  # Prevent comparing a DataSummary with itself
                check=~models.Q(summary_1=models.F("summary_2")),
                name="prevent_self_comparison",
            ),
            models.UniqueConstraint(  # Ensure uniqueness of comparisons
                fields=["summary_1", "summary_2", "comparison_type"],
                name="unique_summary_comparison",
            ),
        ]
        verbose_name = "Summary Comparison"
        verbose_name_plural = "Summary Comparisons"
