from django.db import models
from common.behaviors.timestampable import (
    Timestampable,
)  # Adds created_at and updated_at fields
from common.behaviors.uuidable import UUIDable  # Adds a UUID primary key field
from common.behaviors.annotatable import Annotatable  # Adds annotation capabilities
from common.behaviors.authorable import (
    Authorable,
)  # Adds an author field linked to User


class DataSummary(UUIDable, Timestampable, Annotatable, Authorable):
    # Model representing a summary of a dataset with key metrics and a description.

    label = models.CharField(
        max_length=50,
        help_text="A label identifying the dataset (e.g., 'Week 1').",
    )  # Short label for the dataset

    plain_summary = models.TextField(
        help_text="An English summary of the dataset."
    )  # Text summary generated by ChatGPT

    key_metrics = models.JSONField(
        help_text="Structured key metrics from the dataset."
    )  # Key metrics in JSON format

    metadata = models.JSONField(
        null=True,
        blank=True,
        help_text="Additional metadata about the summary (e.g., filters applied).",
    )  # Optional metadata

    def __str__(self):
        return f"DataSummary: {self.label}"

    class Meta:
        ordering = ["-created_at"]  # Order by most recently created
        verbose_name = "Data Summary"
        verbose_name_plural = "Data Summaries"
