# apps/insights/models/summary.py
from django.db import models

# Uncomment the necessary mixins once their import paths are fixed
# from apps.common.behaviors.timestampable import Timestampable  # Adds created_at and updated_at fields
# from apps.common.behaviors.uuidable import UUIDable  # Adds a UUID primary key field
# from apps.common.behaviors.annotatable import Annotatable  # Adds annotation capabilities
# from apps.common.behaviors.authorable import Authorable  # Adds an author field linked to User


# Model representing a summary of a dataset with key metrics and a description.
class DataSummary(
    models.Model
):  # Add Uuidable mixin, Timestampable, Annotatable, Authorable

    # Short label for the dataset
    label = models.CharField(
        max_length=50,
        help_text="A label identifying the dataset (e.g., 'Week 1').",
    )

    # Text summary generated by ChatGPT
    plain_summary = models.TextField(help_text="An English summary of the dataset.")

    # Key metrics in JSON format
    key_metrics = models.JSONField(help_text="Structured key metrics from the dataset.")

    # Optional metadata
    metadata = models.JSONField(
        null=True,
        blank=True,
        help_text="Additional metadata about the summary (e.g., filters applied).",
    )

    def __str__(self):
        return f"DataSummary: {self.label}"

    class Meta:
        # ordering = ["-created_at"]  # Order by most recently created
        verbose_name = "Data Summary"
        verbose_name_plural = "Data Summaries"
