# Generated by Django 5.1.7 on 2025-04-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="USD", help_text="Currency code (USD, EUR, etc.)", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, default="", help_text="Stripe customer ID", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe payment intent ID",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Credit/Debit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("apple_pay", "Apple Pay"),
                    ("google_pay", "Google Pay"),
                    ("paypal", "PayPal"),
                ],
                default="",
                help_text="Payment method used",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe payment intent ID (legacy)",
                max_length=255,
            ),
        ),
    ]
