# Generated by Django 5.1.7 on 2025-03-27 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_add_s3_fields_to_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("FRONTEND", "Frontend"),
                            ("BACKEND", "Backend"),
                            ("API", "API"),
                            ("DATABASE", "Database"),
                            ("PERFORMANCE", "Performance"),
                            ("SECURITY", "Security"),
                            ("DOCUMENTATION", "Documentation"),
                            ("TESTING", "Testing"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("BLOCKED", "Blocked"),
                            ("DONE", "Done"),
                        ],
                        default="TODO",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Todo Item",
                "verbose_name_plural": "Todo Items",
                "ordering": ["-priority", "due_at", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="upload",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Upload",
                "verbose_name_plural": "Uploads",
            },
        ),
        migrations.RenameIndex(
            model_name="upload",
            new_name="common_uplo_status_3034b6_idx",
            old_name="common_uplo_status_18bb1a_idx",
        ),
        migrations.RenameIndex(
            model_name="upload",
            new_name="common_uplo_s3_buck_f2d3cf_idx",
            old_name="common_uplo_s3_buck_b4eae4_idx",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_todos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
