# Generated by Django 5.1.7 on 2025-03-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_user_has_payment_method_user_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.TextField(blank=True, default="", verbose_name="Biography"),
        ),
    ]
