# Generated by Django 5.1.7 on 2025-03-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_alter_blogpost_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_payment_method",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stripe_customer_id",
        ),
    ]
