# Generated by Django 5.1.7 on 2025-04-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_add_back_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="plan_description",
            field=models.TextField(
                blank=True, default="", help_text="Description of the subscription plan"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, default="", help_text="Stripe customer ID", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe subscription ID",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_price_id",
            field=models.CharField(
                blank=True, default="", help_text="Stripe price ID", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe subscription ID (legacy)",
                max_length=255,
            ),
        ),
    ]
