# Generated by Django 3.2.5 on 2021-08-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_address_country_currency_note_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('to_number', models.CharField(max_length=15)),
                ('from_number', models.CharField(blank=True, max_length=15, null=True)),
                ('body', models.TextField(default='')),
                ('sent_at', models.DateTimeField(null=True)),
                ('read_at', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('to_address', models.CharField(max_length=140)),
                ('from_address', models.CharField(default='NSP <bookings@naturalselectionpromotions.com>', max_length=140)),
                ('subject', models.TextField(max_length=140)),
                ('body', models.TextField(default='')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, 'notification'), (1, 'confirmation'), (2, 'password')], default=0, null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('attachments', models.ManyToManyField(to='common.Upload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
