# Generated by Django 5.1.7 on 2025-03-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Agent",
        ),
        migrations.DeleteModel(
            name="AICompletion",
        ),
        migrations.DeleteModel(
            name="PromptTemplate",
        ),
    ]
