# Generated by Django 5.1.3 on 2024-11-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparison',
            name='end_date',
        ),
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together={('start_date',)},
        ),
        migrations.RemoveField(
            model_name='summary',
            name='end_date',
        ),
    ]
