# Generated by Django 5.1.3 on 2024-11-25 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_remove_comparison_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='start_date',
            field=models.DateField(editable=False, help_text='Start date of the current week in the comparison, derived from summary1.'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='summary1',
            field=models.ForeignKey(help_text='The current week summary being compared.', on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_summary1', to='insights.summary'),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='summary2',
            field=models.ForeignKey(help_text='The past week summary being compared.', on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_summary2', to='insights.summary'),
        ),
        migrations.AlterField(
            model_name='keymetriccomparison',
            name='value1',
            field=models.FloatField(help_text='Value from the current week.'),
        ),
        migrations.AlterField(
            model_name='keymetriccomparison',
            name='value2',
            field=models.FloatField(help_text='Value from the past week.'),
        ),
    ]
