name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          # Install directly from requirements files
          pip install -r requirements/base.lock.txt
          pip install -r requirements/dev.lock.txt
          # Install additional linting tools
          pip install black flake8 mypy django-stubs isort python-dotenv
      
      - name: Format code with Black
        run: black . --check

      - name: Format imports with isort
        run: isort --profile black . --check
        
      - name: Lint with flake8
        run: flake8 . || true  # Continue even if flake8 finds issues
      
      - name: Type check with mypy
        run: mypy . || true  # Continue even if mypy finds issues