name: Lint and Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          ./requirements/install.sh dev
          pip install black flake8 mypy django-stubs isort
      
      - name: Check code formatting with Black
        run: black --check .
      
      - name: Check imports with isort
        run: isort --check-only --profile black .
      
      - name: Lint with flake8
        run: flake8 .
      
      - name: Type check with mypy
        run: mypy .
  
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          ./requirements/install.sh dev
          pip install bandit safety
      
      - name: Check for security vulnerabilities with Bandit
        run: bandit -r apps/ settings/
      
      - name: Check dependencies for known vulnerabilities
        run: safety check -r requirements/prod.txt